/**
 * Pedestrian Plugin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAll_vals_position.h
 *
 * 
 */

#ifndef OAIAll_vals_position_H
#define OAIAll_vals_position_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIAll_vals_position : public OAIObject {
public:
    OAIAll_vals_position();
    OAIAll_vals_position(QString json);
    ~OAIAll_vals_position() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    double getLat() const;
    void setLat(const double &lat);
    bool is_lat_Set() const;
    bool is_lat_Valid() const;

    double getLon() const;
    void setLon(const double &lon);
    bool is_lon_Set() const;
    bool is_lon_Valid() const;

    double getElevation() const;
    void setElevation(const double &elevation);
    bool is_elevation_Set() const;
    bool is_elevation_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    double lat;
    bool m_lat_isSet;
    bool m_lat_isValid;

    double lon;
    bool m_lon_isSet;
    bool m_lon_isValid;

    double elevation;
    bool m_elevation_isSet;
    bool m_elevation_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIAll_vals_position)

#endif // OAIAll_vals_position_H
