/**
 * Pedestrian Plugin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAll_vals_pathPrediction.h
 *
 * 
 */

#ifndef OAIAll_vals_pathPrediction_H
#define OAIAll_vals_pathPrediction_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIAll_vals_pathPrediction : public OAIObject {
public:
    OAIAll_vals_pathPrediction();
    OAIAll_vals_pathPrediction(QString json);
    ~OAIAll_vals_pathPrediction() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    double getRadiusOfCurve() const;
    void setRadiusOfCurve(const double &radius_of_curve);
    bool is_radius_of_curve_Set() const;
    bool is_radius_of_curve_Valid() const;

    double getConfidence() const;
    void setConfidence(const double &confidence);
    bool is_confidence_Set() const;
    bool is_confidence_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    double radius_of_curve;
    bool m_radius_of_curve_isSet;
    bool m_radius_of_curve_isValid;

    double confidence;
    bool m_confidence_isSet;
    bool m_confidence_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIAll_vals_pathPrediction)

#endif // OAIAll_vals_pathPrediction_H
