/**
 * Pedestrian Plugin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAll_vals.h
 *
 * 
 */

#ifndef OAIAll_vals_H
#define OAIAll_vals_H

#include <QJsonObject>

#include "OAIAll_vals_accelSet.h"
#include "OAIAll_vals_accuracy.h"
#include "OAIAll_vals_pathPrediction.h"
#include "OAIAll_vals_position.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIAll_vals : public OAIObject {
public:
    OAIAll_vals();
    OAIAll_vals(QString json);
    ~OAIAll_vals() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    double getBasicType() const;
    void setBasicType(const double &basic_type);
    bool is_basic_type_Set() const;
    bool is_basic_type_Valid() const;

    double getSecMark() const;
    void setSecMark(const double &sec_mark);
    bool is_sec_mark_Set() const;
    bool is_sec_mark_Valid() const;

    double getMsgCnt() const;
    void setMsgCnt(const double &msg_cnt);
    bool is_msg_cnt_Set() const;
    bool is_msg_cnt_Valid() const;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    OAIAll_vals_position getPosition() const;
    void setPosition(const OAIAll_vals_position &position);
    bool is_position_Set() const;
    bool is_position_Valid() const;

    OAIAll_vals_accuracy getAccuracy() const;
    void setAccuracy(const OAIAll_vals_accuracy &accuracy);
    bool is_accuracy_Set() const;
    bool is_accuracy_Valid() const;

    double getSpeed() const;
    void setSpeed(const double &speed);
    bool is_speed_Set() const;
    bool is_speed_Valid() const;

    double getHeading() const;
    void setHeading(const double &heading);
    bool is_heading_Set() const;
    bool is_heading_Valid() const;

    OAIAll_vals_accelSet getAccelSet() const;
    void setAccelSet(const OAIAll_vals_accelSet &accel_set);
    bool is_accel_set_Set() const;
    bool is_accel_set_Valid() const;

    OAIAll_vals_pathPrediction getPathPrediction() const;
    void setPathPrediction(const OAIAll_vals_pathPrediction &path_prediction);
    bool is_path_prediction_Set() const;
    bool is_path_prediction_Valid() const;

    QString getUseState() const;
    void setUseState(const QString &use_state);
    bool is_use_state_Set() const;
    bool is_use_state_Valid() const;

    bool isCrossRequest() const;
    void setCrossRequest(const bool &cross_request);
    bool is_cross_request_Set() const;
    bool is_cross_request_Valid() const;

    bool isCrossState() const;
    void setCrossState(const bool &cross_state);
    bool is_cross_state_Set() const;
    bool is_cross_state_Valid() const;

    double getClusterSize() const;
    void setClusterSize(const double &cluster_size);
    bool is_cluster_size_Set() const;
    bool is_cluster_size_Valid() const;

    double getClusterRadius() const;
    void setClusterRadius(const double &cluster_radius);
    bool is_cluster_radius_Set() const;
    bool is_cluster_radius_Valid() const;

    QString getEventResponderType() const;
    void setEventResponderType(const QString &event_responder_type);
    bool is_event_responder_type_Set() const;
    bool is_event_responder_type_Valid() const;

    QString getActivityType() const;
    void setActivityType(const QString &activity_type);
    bool is_activity_type_Set() const;
    bool is_activity_type_Valid() const;

    QString getActivitySubType() const;
    void setActivitySubType(const QString &activity_sub_type);
    bool is_activity_sub_type_Set() const;
    bool is_activity_sub_type_Valid() const;

    QString getAssistType() const;
    void setAssistType(const QString &assist_type);
    bool is_assist_type_Set() const;
    bool is_assist_type_Valid() const;

    QString getSizing() const;
    void setSizing(const QString &sizing);
    bool is_sizing_Set() const;
    bool is_sizing_Valid() const;

    QString getAttachment() const;
    void setAttachment(const QString &attachment);
    bool is_attachment_Set() const;
    bool is_attachment_Valid() const;

    double getAttachmentRadius() const;
    void setAttachmentRadius(const double &attachment_radius);
    bool is_attachment_radius_Set() const;
    bool is_attachment_radius_Valid() const;

    QString getAnimalType() const;
    void setAnimalType(const QString &animal_type);
    bool is_animal_type_Set() const;
    bool is_animal_type_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    double basic_type;
    bool m_basic_type_isSet;
    bool m_basic_type_isValid;

    double sec_mark;
    bool m_sec_mark_isSet;
    bool m_sec_mark_isValid;

    double msg_cnt;
    bool m_msg_cnt_isSet;
    bool m_msg_cnt_isValid;

    QString id;
    bool m_id_isSet;
    bool m_id_isValid;

    OAIAll_vals_position position;
    bool m_position_isSet;
    bool m_position_isValid;

    OAIAll_vals_accuracy accuracy;
    bool m_accuracy_isSet;
    bool m_accuracy_isValid;

    double speed;
    bool m_speed_isSet;
    bool m_speed_isValid;

    double heading;
    bool m_heading_isSet;
    bool m_heading_isValid;

    OAIAll_vals_accelSet accel_set;
    bool m_accel_set_isSet;
    bool m_accel_set_isValid;

    OAIAll_vals_pathPrediction path_prediction;
    bool m_path_prediction_isSet;
    bool m_path_prediction_isValid;

    QString use_state;
    bool m_use_state_isSet;
    bool m_use_state_isValid;

    bool cross_request;
    bool m_cross_request_isSet;
    bool m_cross_request_isValid;

    bool cross_state;
    bool m_cross_state_isSet;
    bool m_cross_state_isValid;

    double cluster_size;
    bool m_cluster_size_isSet;
    bool m_cluster_size_isValid;

    double cluster_radius;
    bool m_cluster_radius_isSet;
    bool m_cluster_radius_isValid;

    QString event_responder_type;
    bool m_event_responder_type_isSet;
    bool m_event_responder_type_isValid;

    QString activity_type;
    bool m_activity_type_isSet;
    bool m_activity_type_isValid;

    QString activity_sub_type;
    bool m_activity_sub_type_isSet;
    bool m_activity_sub_type_isValid;

    QString assist_type;
    bool m_assist_type_isSet;
    bool m_assist_type_isValid;

    QString sizing;
    bool m_sizing_isSet;
    bool m_sizing_isValid;

    QString attachment;
    bool m_attachment_isSet;
    bool m_attachment_isValid;

    double attachment_radius;
    bool m_attachment_radius_isSet;
    bool m_attachment_radius_isValid;

    QString animal_type;
    bool m_animal_type_isSet;
    bool m_animal_type_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIAll_vals)

#endif // OAIAll_vals_H
