/**
 * Pedestrian Plugin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAll_vals_accelSet.h
 *
 * 
 */

#ifndef OAIAll_vals_accelSet_H
#define OAIAll_vals_accelSet_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIAll_vals_accelSet : public OAIObject {
public:
    OAIAll_vals_accelSet();
    OAIAll_vals_accelSet(QString json);
    ~OAIAll_vals_accelSet() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    double getRLong() const;
    void setRLong(const double &r_long);
    bool is_r_long_Set() const;
    bool is_r_long_Valid() const;

    double getLat() const;
    void setLat(const double &lat);
    bool is_lat_Set() const;
    bool is_lat_Valid() const;

    double getVert() const;
    void setVert(const double &vert);
    bool is_vert_Set() const;
    bool is_vert_Valid() const;

    double getYaw() const;
    void setYaw(const double &yaw);
    bool is_yaw_Set() const;
    bool is_yaw_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    double r_long;
    bool m_r_long_isSet;
    bool m_r_long_isValid;

    double lat;
    bool m_lat_isSet;
    bool m_lat_isValid;

    double vert;
    bool m_vert_isSet;
    bool m_vert_isValid;

    double yaw;
    bool m_yaw_isSet;
    bool m_yaw_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIAll_vals_accelSet)

#endif // OAIAll_vals_accelSet_H
