/**
 * Pedestrian Plugin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIMessage_value.h
 *
 * PSM payload
 */

#ifndef OAIMessage_value_H
#define OAIMessage_value_H

#include <QJsonObject>

#include "OAIAll_vals.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIMessage_value : public OAIObject {
public:
    OAIMessage_value();
    OAIMessage_value(QString json);
    ~OAIMessage_value() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIAll_vals getAllVals() const;
    void setAllVals(const OAIAll_vals &all_vals);
    bool is_all_vals_Set() const;
    bool is_all_vals_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIAll_vals all_vals;
    bool m_all_vals_isSet;
    bool m_all_vals_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIMessage_value)

#endif // OAIMessage_value_H
