/**
 * Pedestrian Plugin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIMessage_frame.h
 *
 * The message frame
 */

#ifndef OAIMessage_frame_H
#define OAIMessage_frame_H

#include <QJsonObject>

#include "OAIMessage_value.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIMessage_frame : public OAIObject {
public:
    OAIMessage_frame();
    OAIMessage_frame(QString json);
    ~OAIMessage_frame() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    double getMessageId() const;
    void setMessageId(const double &message_id);
    bool is_message_id_Set() const;
    bool is_message_id_Valid() const;

    OAIMessage_value getMessageValue() const;
    void setMessageValue(const OAIMessage_value &message_value);
    bool is_message_value_Set() const;
    bool is_message_value_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    double message_id;
    bool m_message_id_isSet;
    bool m_message_id_isValid;

    OAIMessage_value message_value;
    bool m_message_value_isSet;
    bool m_message_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIMessage_frame)

#endif // OAIMessage_frame_H
