/**
 * Pedestrian Plugin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIPersonalSafetyMessage_accuracy.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIPersonalSafetyMessage_accuracy::OAIPersonalSafetyMessage_accuracy(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIPersonalSafetyMessage_accuracy::OAIPersonalSafetyMessage_accuracy() {
    this->initializeModel();
}

OAIPersonalSafetyMessage_accuracy::~OAIPersonalSafetyMessage_accuracy() {}

void OAIPersonalSafetyMessage_accuracy::initializeModel() {

    m_semi_major_isSet = false;
    m_semi_major_isValid = false;

    m_semi_minor_isSet = false;
    m_semi_minor_isValid = false;

    m_orientation_isSet = false;
    m_orientation_isValid = false;
}

void OAIPersonalSafetyMessage_accuracy::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIPersonalSafetyMessage_accuracy::fromJsonObject(QJsonObject json) {

    m_semi_major_isValid = ::OpenAPI::fromJsonValue(semi_major, json[QString("semiMajor")]);
    m_semi_major_isSet = !json[QString("semiMajor")].isNull() && m_semi_major_isValid;

    m_semi_minor_isValid = ::OpenAPI::fromJsonValue(semi_minor, json[QString("semiMinor")]);
    m_semi_minor_isSet = !json[QString("semiMinor")].isNull() && m_semi_minor_isValid;

    m_orientation_isValid = ::OpenAPI::fromJsonValue(orientation, json[QString("orientation")]);
    m_orientation_isSet = !json[QString("orientation")].isNull() && m_orientation_isValid;
}

QString OAIPersonalSafetyMessage_accuracy::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIPersonalSafetyMessage_accuracy::asJsonObject() const {
    QJsonObject obj;
    if (m_semi_major_isSet) {
        obj.insert(QString("semiMajor"), ::OpenAPI::toJsonValue(semi_major));
    }
    if (m_semi_minor_isSet) {
        obj.insert(QString("semiMinor"), ::OpenAPI::toJsonValue(semi_minor));
    }
    if (m_orientation_isSet) {
        obj.insert(QString("orientation"), ::OpenAPI::toJsonValue(orientation));
    }
    return obj;
}

double OAIPersonalSafetyMessage_accuracy::getSemiMajor() const {
    return semi_major;
}
void OAIPersonalSafetyMessage_accuracy::setSemiMajor(const double &semi_major) {
    this->semi_major = semi_major;
    this->m_semi_major_isSet = true;
}

bool OAIPersonalSafetyMessage_accuracy::is_semi_major_Set() const{
    return m_semi_major_isSet;
}

bool OAIPersonalSafetyMessage_accuracy::is_semi_major_Valid() const{
    return m_semi_major_isValid;
}

double OAIPersonalSafetyMessage_accuracy::getSemiMinor() const {
    return semi_minor;
}
void OAIPersonalSafetyMessage_accuracy::setSemiMinor(const double &semi_minor) {
    this->semi_minor = semi_minor;
    this->m_semi_minor_isSet = true;
}

bool OAIPersonalSafetyMessage_accuracy::is_semi_minor_Set() const{
    return m_semi_minor_isSet;
}

bool OAIPersonalSafetyMessage_accuracy::is_semi_minor_Valid() const{
    return m_semi_minor_isValid;
}

double OAIPersonalSafetyMessage_accuracy::getOrientation() const {
    return orientation;
}
void OAIPersonalSafetyMessage_accuracy::setOrientation(const double &orientation) {
    this->orientation = orientation;
    this->m_orientation_isSet = true;
}

bool OAIPersonalSafetyMessage_accuracy::is_orientation_Set() const{
    return m_orientation_isSet;
}

bool OAIPersonalSafetyMessage_accuracy::is_orientation_Valid() const{
    return m_orientation_isValid;
}

bool OAIPersonalSafetyMessage_accuracy::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_semi_major_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_semi_minor_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_orientation_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIPersonalSafetyMessage_accuracy::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_semi_major_isValid && m_semi_minor_isValid && m_orientation_isValid && true;
}

} // namespace OpenAPI
