/**
 * Pedestrian Plugin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIPsm.h
 *
 * 
 */

#ifndef OAIPsm_H
#define OAIPsm_H

#include <QJsonObject>

#include "OAIPsm_info.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIPsm : public OAIObject {
public:
    OAIPsm();
    OAIPsm(QString json);
    ~OAIPsm() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIPsm_info getPsmInfo() const;
    void setPsmInfo(const OAIPsm_info &psm_info);
    bool is_psm_info_Set() const;
    bool is_psm_info_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIPsm_info psm_info;
    bool m_psm_info_isSet;
    bool m_psm_info_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIPsm)

#endif // OAIPsm_H
