/**
 * Pedestrian Plugin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIPsm_info.h
 *
 * The entire PSM message including message identifier
 */

#ifndef OAIPsm_info_H
#define OAIPsm_info_H

#include <QJsonObject>

#include "OAIMessage_frame.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIPsm_info : public OAIObject {
public:
    OAIPsm_info();
    OAIPsm_info(QString json);
    ~OAIPsm_info() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIMessage_frame getMessageFrame() const;
    void setMessageFrame(const OAIMessage_frame &message_frame);
    bool is_message_frame_Set() const;
    bool is_message_frame_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIMessage_frame message_frame;
    bool m_message_frame_isSet;
    bool m_message_frame_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIPsm_info)

#endif // OAIPsm_info_H
