/**
 * Pedestrian Plugin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIPsm_info.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIPsm_info::OAIPsm_info(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIPsm_info::OAIPsm_info() {
    this->initializeModel();
}

OAIPsm_info::~OAIPsm_info() {}

void OAIPsm_info::initializeModel() {

    m_message_frame_isSet = false;
    m_message_frame_isValid = false;
}

void OAIPsm_info::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIPsm_info::fromJsonObject(QJsonObject json) {

    m_message_frame_isValid = ::OpenAPI::fromJsonValue(message_frame, json[QString("message_frame")]);
    m_message_frame_isSet = !json[QString("message_frame")].isNull() && m_message_frame_isValid;
}

QString OAIPsm_info::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIPsm_info::asJsonObject() const {
    QJsonObject obj;
    if (message_frame.isSet()) {
        obj.insert(QString("message_frame"), ::OpenAPI::toJsonValue(message_frame));
    }
    return obj;
}

OAIMessage_frame OAIPsm_info::getMessageFrame() const {
    return message_frame;
}
void OAIPsm_info::setMessageFrame(const OAIMessage_frame &message_frame) {
    this->message_frame = message_frame;
    this->m_message_frame_isSet = true;
}

bool OAIPsm_info::is_message_frame_Set() const{
    return m_message_frame_isSet;
}

bool OAIPsm_info::is_message_frame_Valid() const{
    return m_message_frame_isValid;
}

bool OAIPsm_info::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (message_frame.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIPsm_info::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_message_frame_isValid && true;
}

} // namespace OpenAPI
