/**
 * Pedestrian Plugin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIPersonalSafetyMessage_accelSet.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIPersonalSafetyMessage_accelSet::OAIPersonalSafetyMessage_accelSet(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIPersonalSafetyMessage_accelSet::OAIPersonalSafetyMessage_accelSet() {
    this->initializeModel();
}

OAIPersonalSafetyMessage_accelSet::~OAIPersonalSafetyMessage_accelSet() {}

void OAIPersonalSafetyMessage_accelSet::initializeModel() {

    m_r_long_isSet = false;
    m_r_long_isValid = false;

    m_lat_isSet = false;
    m_lat_isValid = false;

    m_vert_isSet = false;
    m_vert_isValid = false;

    m_yaw_isSet = false;
    m_yaw_isValid = false;
}

void OAIPersonalSafetyMessage_accelSet::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIPersonalSafetyMessage_accelSet::fromJsonObject(QJsonObject json) {

    m_r_long_isValid = ::OpenAPI::fromJsonValue(r_long, json[QString("long")]);
    m_r_long_isSet = !json[QString("long")].isNull() && m_r_long_isValid;

    m_lat_isValid = ::OpenAPI::fromJsonValue(lat, json[QString("lat")]);
    m_lat_isSet = !json[QString("lat")].isNull() && m_lat_isValid;

    m_vert_isValid = ::OpenAPI::fromJsonValue(vert, json[QString("vert")]);
    m_vert_isSet = !json[QString("vert")].isNull() && m_vert_isValid;

    m_yaw_isValid = ::OpenAPI::fromJsonValue(yaw, json[QString("yaw")]);
    m_yaw_isSet = !json[QString("yaw")].isNull() && m_yaw_isValid;
}

QString OAIPersonalSafetyMessage_accelSet::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIPersonalSafetyMessage_accelSet::asJsonObject() const {
    QJsonObject obj;
    if (m_r_long_isSet) {
        obj.insert(QString("long"), ::OpenAPI::toJsonValue(r_long));
    }
    if (m_lat_isSet) {
        obj.insert(QString("lat"), ::OpenAPI::toJsonValue(lat));
    }
    if (m_vert_isSet) {
        obj.insert(QString("vert"), ::OpenAPI::toJsonValue(vert));
    }
    if (m_yaw_isSet) {
        obj.insert(QString("yaw"), ::OpenAPI::toJsonValue(yaw));
    }
    return obj;
}

double OAIPersonalSafetyMessage_accelSet::getRLong() const {
    return r_long;
}
void OAIPersonalSafetyMessage_accelSet::setRLong(const double &r_long) {
    this->r_long = r_long;
    this->m_r_long_isSet = true;
}

bool OAIPersonalSafetyMessage_accelSet::is_r_long_Set() const{
    return m_r_long_isSet;
}

bool OAIPersonalSafetyMessage_accelSet::is_r_long_Valid() const{
    return m_r_long_isValid;
}

double OAIPersonalSafetyMessage_accelSet::getLat() const {
    return lat;
}
void OAIPersonalSafetyMessage_accelSet::setLat(const double &lat) {
    this->lat = lat;
    this->m_lat_isSet = true;
}

bool OAIPersonalSafetyMessage_accelSet::is_lat_Set() const{
    return m_lat_isSet;
}

bool OAIPersonalSafetyMessage_accelSet::is_lat_Valid() const{
    return m_lat_isValid;
}

double OAIPersonalSafetyMessage_accelSet::getVert() const {
    return vert;
}
void OAIPersonalSafetyMessage_accelSet::setVert(const double &vert) {
    this->vert = vert;
    this->m_vert_isSet = true;
}

bool OAIPersonalSafetyMessage_accelSet::is_vert_Set() const{
    return m_vert_isSet;
}

bool OAIPersonalSafetyMessage_accelSet::is_vert_Valid() const{
    return m_vert_isValid;
}

double OAIPersonalSafetyMessage_accelSet::getYaw() const {
    return yaw;
}
void OAIPersonalSafetyMessage_accelSet::setYaw(const double &yaw) {
    this->yaw = yaw;
    this->m_yaw_isSet = true;
}

bool OAIPersonalSafetyMessage_accelSet::is_yaw_Set() const{
    return m_yaw_isSet;
}

bool OAIPersonalSafetyMessage_accelSet::is_yaw_Valid() const{
    return m_yaw_isValid;
}

bool OAIPersonalSafetyMessage_accelSet::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_r_long_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_lat_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_vert_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_yaw_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIPersonalSafetyMessage_accelSet::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
