/**
 * Pedestrian Plugin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIPsm.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIPsm::OAIPsm(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIPsm::OAIPsm() {
    this->initializeModel();
}

OAIPsm::~OAIPsm() {}

void OAIPsm::initializeModel() {

    m_psm_info_isSet = false;
    m_psm_info_isValid = false;
}

void OAIPsm::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIPsm::fromJsonObject(QJsonObject json) {

    m_psm_info_isValid = ::OpenAPI::fromJsonValue(psm_info, json[QString("psm_info")]);
    m_psm_info_isSet = !json[QString("psm_info")].isNull() && m_psm_info_isValid;
}

QString OAIPsm::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIPsm::asJsonObject() const {
    QJsonObject obj;
    if (psm_info.isSet()) {
        obj.insert(QString("psm_info"), ::OpenAPI::toJsonValue(psm_info));
    }
    return obj;
}

OAIPsm_info OAIPsm::getPsmInfo() const {
    return psm_info;
}
void OAIPsm::setPsmInfo(const OAIPsm_info &psm_info) {
    this->psm_info = psm_info;
    this->m_psm_info_isSet = true;
}

bool OAIPsm::is_psm_info_Set() const{
    return m_psm_info_isSet;
}

bool OAIPsm::is_psm_info_Valid() const{
    return m_psm_info_isValid;
}

bool OAIPsm::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (psm_info.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIPsm::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_psm_info_isValid && true;
}

} // namespace OpenAPI
